org: dsalaverryyy
service: utec-diagram-backend

provider:
  name: aws
  runtime: python3.13
  memorySize: 256  
  timeout: 30      
  stage: dev
  region: us-east-1
  iam:
    role: arn:aws:iam::570699102669:role/LabRole  

layers:
  graphviz:
    arn: arn:aws:lambda:us-east-1:553035198032:layer:graphviz:10

functions:
  crearUsuario:
    handler: handler.crearUsuario
    memorySize: 512
    layers:
      - ${self:layers.graphviz}
    events:
      - http:
          path: usuarios
          method: post
          cors: true
          integration: lambda

  loginUsuario:
    handler: handler.loginUsuario
    memorySize: 512
    layers:
      - ${self:layers.graphviz}
    events:
      - http:
          path: login
          method: post
          cors: true
          integration: lambda

  validarTokenAcceso:
    handler: handler.validarTokenAcceso
    memorySize: 512
    layers:
      - ${self:layers.graphviz}
    events:
      - http:
          path: validar-token
          method: post
          cors: true
          integration: lambda

  generarDiagrama:
    handler: handler.generarDiagrama
    memorySize: 512
    layers:
      - ${self:layers.graphviz}
    events:
      - http:
          path: generar-diagrama
          method: post
          cors: true
          integration: lambda

  validarDiagrama:
    handler: handler.validarDiagrama
    memorySize: 512
    layers:
      - ${self:layers.graphviz}
    events:
      - http:
          path: validar-diagrama
          method: post
          cors: true
          integration: lambda

  guardarDiagramaS3:
    handler: handler.guardarDiagramaS3
    memorySize: 512
    layers:
      - ${self:layers.graphviz}
    events:
      - http:
          path: guardar-diagrama
          method: post
          cors: true
          integration: lambda
